-- Migration: Hybrid Inventory System

-- 1. Create the ingredients table
CREATE TABLE IF NOT EXISTS public.ingredients (
    id TEXT PRIMARY KEY, -- CUID generated by the Next.js client
    name TEXT NOT NULL,
    unit TEXT NOT NULL, -- 'kg', 'lt', 'unit', 'gr', 'ml'
    current_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
    minimum_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost_per_unit DOUBLE PRECISION,
    tracking_type TEXT NOT NULL DEFAULT 'MEASURABLE' CHECK (tracking_type IN ('PIECE', 'MEASURABLE')),
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for ingredients
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Scoped access for ingredients" ON public.ingredients
    FOR ALL USING (tenant_id = COALESCE(
        (SELECT profiles.tenant_id FROM profiles WHERE profiles.id = auth.uid()),
        (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid,
        (SELECT id FROM tenants WHERE slug = 'tesorito' LIMIT 1)
    ));

-- 2. Alter menu_items to add ingredient_id
ALTER TABLE public.menu_items 
ADD COLUMN IF NOT EXISTS ingredient_id TEXT REFERENCES public.ingredients(id) ON DELETE SET NULL;

-- 3. Recreate recipe_items to link to ingredients
DROP TABLE IF EXISTS public.recipe_items;

CREATE TABLE public.recipe_items (
    id TEXT PRIMARY KEY, -- CUID generated by Next.js client
    menu_item_id TEXT NOT NULL REFERENCES public.menu_items(id) ON DELETE CASCADE,
    ingredient_id TEXT NOT NULL REFERENCES public.ingredients(id) ON DELETE CASCADE,
    quantity_required DOUBLE PRECISION NOT NULL,
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    UNIQUE(menu_item_id, ingredient_id)
);

-- Enable RLS for recipe_items
ALTER TABLE public.recipe_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Scoped access for recipe_items" ON public.recipe_items
    FOR ALL USING (tenant_id = COALESCE(
        (SELECT profiles.tenant_id FROM profiles WHERE profiles.id = auth.uid()),
        (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid,
        (SELECT id FROM tenants WHERE slug = 'tesorito' LIMIT 1)
    ));

-- 4. Create the stock_adjustments table
CREATE TABLE IF NOT EXISTS public.stock_adjustments (
    id TEXT PRIMARY KEY,
    ingredient_id TEXT REFERENCES public.ingredients(id) ON DELETE CASCADE,
    menu_item_id TEXT REFERENCES public.menu_items(id) ON DELETE CASCADE,
    adjustment DOUBLE PRECISION NOT NULL, -- positive (purchase) or negative (correction/waste)
    reason TEXT, -- 'Compra', 'Venta', 'Merma', 'Corrección'
    tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for stock_adjustments
ALTER TABLE public.stock_adjustments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Scoped access for stock_adjustments" ON public.stock_adjustments
    FOR ALL USING (tenant_id = COALESCE(
        (SELECT profiles.tenant_id FROM profiles WHERE profiles.id = auth.uid()),
        (NULLIF(current_setting('app.current_tenant_id'::text, true), ''::text))::uuid,
        (SELECT id FROM tenants WHERE slug = 'tesorito' LIMIT 1)
    ));
