-- =====================================================================
-- TESORITO OS - BASE DATABASE INITIALIZATION SCRIPT FOR SUPABASE
-- Run this in your Supabase SQL Editor to configure all tables,
-- relationships, Row-Level Security (RLS) policies, and auth triggers.
-- =====================================================================

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =====================================================================
-- 1. AUTHENTICATION & PROFILES MODULE
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    full_name TEXT,
    role TEXT DEFAULT 'WAITER', -- 'ADMIN', 'MANAGER', 'WAITER', 'CHEF'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Allow all operations for anon/authenticated users (adjust in production)
CREATE POLICY "Allow all operations for anon on profiles" ON public.profiles FOR ALL USING (true);

-- Trigger to automatically create a profile on new auth user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', 'Sin nombre'),
    COALESCE(new.raw_user_meta_data->>'role', 'WAITER')
  )
  ON CONFLICT (id) DO UPDATE
  SET email = EXCLUDED.email,
      full_name = EXCLUDED.full_name,
      role = EXCLUDED.role;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create the trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- =====================================================================
-- 2. INVENTORY & RECIPES MODULE
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.ingredients (
    id TEXT PRIMARY KEY, -- CUID generated by Next.js client
    name TEXT NOT NULL,
    unit TEXT NOT NULL, -- 'kg', 'lt', 'unit', 'gr', 'ml'
    current_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
    minimum_stock DOUBLE PRECISION NOT NULL DEFAULT 0,
    cost_per_unit DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.menu_items (
    id TEXT PRIMARY KEY, -- CUID generated by Next.js client
    name TEXT NOT NULL,
    description TEXT,
    price DOUBLE PRECISION NOT NULL,
    category TEXT, -- 'ANTOJITOS', 'TACOS', 'BEBIDAS', etc.
    image_url TEXT,
    is_available BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.recipe_items (
    id TEXT PRIMARY KEY, -- CUID generated by Next.js client
    menu_item_id TEXT NOT NULL REFERENCES public.menu_items(id) ON DELETE CASCADE,
    ingredient_id TEXT NOT NULL REFERENCES public.ingredients(id) ON DELETE CASCADE,
    quantity_required DOUBLE PRECISION NOT NULL,
    UNIQUE(menu_item_id, ingredient_id)
);

CREATE TABLE IF NOT EXISTS public.stock_adjustments (
    id TEXT PRIMARY KEY, -- CUID generated by Next.js client
    ingredient_id TEXT NOT NULL REFERENCES public.ingredients(id) ON DELETE CASCADE,
    adjustment DOUBLE PRECISION NOT NULL, -- positive (purchase) or negative (correction)
    reason TEXT, -- 'Compra', 'Corrección', 'Merma'
    user_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================================
-- 3. CRM & CUSTOMERS MODULE
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.customers (
    id TEXT PRIMARY KEY, -- CUID generated by Next.js client
    name TEXT NOT NULL,
    phone TEXT UNIQUE,
    email TEXT UNIQUE,
    birthday DATE,
    loyalty_points INTEGER DEFAULT 0 NOT NULL,
    total_spend DOUBLE PRECISION DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================================
-- 4. ORDERS & POS MODULE
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY, -- CUID generated by Next.js client
    order_number TEXT UNIQUE NOT NULL, -- Human-readable folio
    customer_id TEXT REFERENCES public.customers(id) ON DELETE SET NULL,
    source TEXT NOT NULL, -- 'TikTok', 'Instagram', 'Pasaba por ahí', 'Recomendación', 'Otro'
    status TEXT DEFAULT 'PENDING' NOT NULL, -- 'PENDING', 'PREPARING', 'READY', 'DELIVERED', 'PAID', 'CANCELLED', 'UNCOLLECTED'
    "table" TEXT,
    notes TEXT,
    subtotal DOUBLE PRECISION DEFAULT 0 NOT NULL,
    tax DOUBLE PRECISION DEFAULT 0 NOT NULL,
    total DOUBLE PRECISION DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS public.order_items (
    id TEXT PRIMARY KEY, -- CUID generated by Next.js client
    order_id TEXT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    menu_item_id TEXT NOT NULL REFERENCES public.menu_items(id) ON DELETE RESTRICT,
    quantity INTEGER DEFAULT 1 NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.order_adjustments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id TEXT REFERENCES public.orders(id) ON DELETE CASCADE,
    previous_status TEXT,
    new_status TEXT,
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================================
-- 5. PAYMENTS & TIPS MODULE
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.payments (
    id TEXT PRIMARY KEY, -- CUID generated by Next.js client
    order_id TEXT UNIQUE NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    method TEXT DEFAULT 'CASH' NOT NULL, -- 'CASH', 'CARD', 'TRANSFER', 'OTHER'
    amount DOUBLE PRECISION NOT NULL,
    received_amount DOUBLE PRECISION,
    change DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.daily_tips (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cut_date DATE UNIQUE NOT NULL,
    total_card_tips NUMERIC(10, 2) DEFAULT 0,
    total_cash_tips NUMERIC(10, 2) DEFAULT 0,
    total_tips NUMERIC(10, 2) DEFAULT 0,
    total_hours NUMERIC(10, 2) DEFAULT 0,
    breakdown JSONB DEFAULT '[]'::JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================================
-- 6. EXPENSES MODULE
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.expense_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    color TEXT DEFAULT '#3B82F6',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.expenses (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id UUID REFERENCES public.expense_categories(id) ON DELETE RESTRICT,
    amount NUMERIC(10, 2) NOT NULL,
    description TEXT NOT NULL,
    has_invoice BOOLEAN DEFAULT FALSE,
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================================
-- 7. OPERATIONS, ATTENDANCE & TASKS MODULE
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.attendance (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    check_in TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    check_out TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'ACTIVE', -- 'ACTIVE', 'FINISHED'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.primordial_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    frequency_type TEXT NOT NULL, -- 'CONTINUOUS', 'VARIABLE', 'ROUTINE', 'DAILY', 'WEEKLY', 'CLOSING'
    requires_photo BOOLEAN DEFAULT FALSE,
    timeout_minutes INTEGER DEFAULT 60,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.task_executions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    task_id UUID REFERENCES public.primordial_tasks(id) ON DELETE RESTRICT,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'PENDING', -- 'PENDING', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'APPROVED'
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    last_resumed_at TIMESTAMP WITH TIME ZONE,
    paused_seconds INTEGER DEFAULT 0,
    net_duration_minutes INTEGER,
    photo_url TEXT,
    approved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.daily_cuts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cut_date DATE NOT NULL UNIQUE,
    venta_neta NUMERIC(10, 2) DEFAULT 0,
    iva_acumulado NUMERIC(10, 2) DEFAULT 0,
    propinas_efectivo NUMERIC(10, 2) DEFAULT 0,
    propinas_tarjeta NUMERIC(10, 2) DEFAULT 0,
    caja_efectivo NUMERIC(10, 2) DEFAULT 0,
    caja_tarjeta NUMERIC(10, 2) DEFAULT 0,
    utilidad_real NUMERIC(10, 2) DEFAULT 0,
    total_gastos NUMERIC(10, 2) DEFAULT 0,
    utilidad_final NUMERIC(10, 2) DEFAULT 0,
    total_orders INTEGER DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- =====================================================================
-- 8. ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================================

-- Enable RLS for all tables
ALTER TABLE public.ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_tips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.primordial_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_cuts ENABLE ROW LEVEL SECURITY;

-- Create basic full-access policies for anon (standard clients connect with anon key)
CREATE POLICY "Allow all for ingredients" ON public.ingredients FOR ALL USING (true);
CREATE POLICY "Allow all for menu_items" ON public.menu_items FOR ALL USING (true);
CREATE POLICY "Allow all for recipe_items" ON public.recipe_items FOR ALL USING (true);
CREATE POLICY "Allow all for stock_adjustments" ON public.stock_adjustments FOR ALL USING (true);
CREATE POLICY "Allow all for customers" ON public.customers FOR ALL USING (true);
CREATE POLICY "Allow all for orders" ON public.orders FOR ALL USING (true);
CREATE POLICY "Allow all for order_items" ON public.order_items FOR ALL USING (true);
CREATE POLICY "Allow all for order_adjustments" ON public.order_adjustments FOR ALL USING (true);
CREATE POLICY "Allow all for payments" ON public.payments FOR ALL USING (true);
CREATE POLICY "Allow all for daily_tips" ON public.daily_tips FOR ALL USING (true);
CREATE POLICY "Allow all for expense_categories" ON public.expense_categories FOR ALL USING (true);
CREATE POLICY "Allow all for expenses" ON public.expenses FOR ALL USING (true);
CREATE POLICY "Allow all for attendance" ON public.attendance FOR ALL USING (true);
CREATE POLICY "Allow all for primordial_tasks" ON public.primordial_tasks FOR ALL USING (true);
CREATE POLICY "Allow all for task_executions" ON public.task_executions FOR ALL USING (true);
CREATE POLICY "Allow all for daily_cuts" ON public.daily_cuts FOR ALL USING (true);


-- =====================================================================
-- 9. SEED DEFAULT DATA
-- =====================================================================

-- Seed expense categories
INSERT INTO public.expense_categories (name, color) 
VALUES 
    ('Insumos', '#10B981'),
    ('Sueldos', '#6366F1'),
    ('Servicios', '#F59E0B'),
    ('Otros', '#6B7280')
ON CONFLICT (name) DO NOTHING;

-- Seed primordial tasks
INSERT INTO public.primordial_tasks (name, frequency_type, requires_photo, timeout_minutes)
VALUES
    ('Lavar los trastes (Evitar acumulación)', 'CONTINUOUS', FALSE, 60),
    ('Desinfectar los cubiertos y armarlos', 'VARIABLE', FALSE, 30),
    ('Limpiar y organizar rack y especias', 'ROUTINE', FALSE, 45),
    ('Limpiar refrigeradores (interior y exterior)', 'VARIABLE', TRUE, 60),
    ('Limpiar parrilla y estufa con fibra', 'DAILY', TRUE, 90),
    ('Limpiar contenedores y tapas', 'DAILY', FALSE, 45),
    ('Limpiar mueble de trastes', 'ROUTINE', FALSE, 30),
    ('Limpiar mueble blanco', 'ROUTINE', FALSE, 30),
    ('Limpiar campana interior/exterior', 'ROUTINE', TRUE, 60),
    ('Mover muebles para limpieza profunda', 'VARIABLE', TRUE, 90),
    ('Barrer y trapear el área', 'VARIABLE', FALSE, 45),
    ('Lavar jerga y dejar en cubeta limpia', 'CLOSING', FALSE, 15),
    ('Lavar trapos de cocina', 'ROUTINE', FALSE, 20),
    ('Limpiar charolas y libritos para cuentas', 'CLOSING', FALSE, 15),
    ('Limpiar maquinaria (Air fryer, licuadora)', 'CLOSING', TRUE, 30)
ON CONFLICT (name) DO NOTHING;

-- =====================================================================
-- 10. OPTIMIZATION INDEXES
-- =====================================================================
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ingredients_stock ON public.ingredients(current_stock);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers(phone);
